### ISSUE TITLE
i run python main.py --model nn --dataset PaviaU --training_sample 0.1 --cuda 1,then it happend

### ISSUE THREAD

**Issue by JoJo-ops** [nshaud/DeepHyperX#1]
Network :
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    summary(model.to(hyperparams['device']), input.size()[1:], device=hyperparams['device'])
  File "/home/xj/anaconda3/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 44, in summary
    device = device.lower()
AttributeError: 'torch.device' object has no attribute 'lower'

**Comment by daniel-rychlewski** [comment]
Try to change the line 
`summary(model.to(hyperparams['device']), input.size()[1:], device=hyperparams['device'])`
in main.py:301 to
`summary(model.to(hyperparams['device']), input.size()[1:])`
This fixed the problem for me & the network architecture is now nicely displayed in the beginning

**Comment by nshaud** [comment]
Thanks, this should be fixed in master.
