### ISSUE TITLE
Blue Screen on visdom, no plots

### ISSUE THREAD

**Issue by ucalyptus** [nshaud/DeepHyperX#11]
![Screenshot from 2020-05-12 18-59-22](https://user-images.githubusercontent.com/36279638/81697540-b9acf280-9482-11ea-9273-f83530fe984f.png)

**Comment by ucalyptus** [comment]
![Screenshot from 2020-05-12 19-01-34](https://user-images.githubusercontent.com/36279638/81697957-04c70580-9483-11ea-8bf3-dc5dcfef8550.png)

**Comment by ucalyptus** [comment]
![Screenshot from 2020-05-12 19-01-32](https://user-images.githubusercontent.com/36279638/81698015-0ee90400-9483-11ea-84a0-046b661ec410.png)

**Comment by ucalyptus** [comment]
@nshaud

**Comment by ghost** [comment]
Hi ucalyptus,

In the top bar of visdom, if you uncheck the main line and check the indian pines line, they should appear.
