### ISSUE TITLE
pip install torch error - Windows 10

### ISSUE THREAD

**Issue by sbaber1** [nshaud/DeepHyperX#14]
Had trouble doing pip install torch using the requirements.txt-- seems to be a Windows issue (https://github.com/pytorch/pytorch/issues/29395) 
Might want to make note of this? Thank you!

**Comment by svlandeg** [comment]
Could you try running `pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html` ?

**Comment by nshaud** [comment]
`pip install torch` is not supported on Windows, @svlandeg suggestion should work. I'll add it to the readme.
