### ISSUE TITLE
Salinas loading

### ISSUE THREAD

**Issue by gxwangupc** [nshaud/DeepHyperX#17]
I have suffered from loading failure before I examine the name of the data.
Now code runs after
#img = open_file(folder + 'Salinas.mat')['Salinas_corrected']
img = open_file(folder + 'Salinas_corrected.mat')['salinas_corrected']
#gt = open_file(folder + 'Salinas_gt.mat')['Salinas_gt']
gt = open_file(folder + 'Salinas_gt.mat')['salinas_gt']

**Comment by GreatBruceYoung** [comment]
Good suggestion! I have settled the issue!!! 
**THANKS!**
