### ISSUE TITLE
How to get stable results?

### ISSUE THREAD

**Issue by likyoo** [nshaud/DeepHyperX#43]
Thanks for your great work!
I run the code and set "--run 10", but the results of each run fluctuate wildly. 
I adjusted lr, batchsize ..., but it didn't work. 
Could you give me some advice? thank you!

**Comment by nshaud** [comment]
Results can fluctuate depending on your splitting scheme. If you have a very imbalanced dataset or if you use a small % for validation, then a high variance in test results is expected.

**Comment by likyoo** [comment]
thanks!
