### ISSUE TITLE
/bin/sh: 0: Can't open start.sh

### ISSUE THREAD

**Issue by 5MI7th3MI6** [nshaud/DeepHyperX#45]
Hello, 

I tried running the container on both Docker and Singularity; however, I am getting this error "/bin/sh: 0: Can't open start.sh". Is there a way to fix this? 

This is the command I ran on Docker `docker run -p 9999:8097 -ti --rm -v `pwd`:/workspace/DeepHyperX/ registry.gitlab.inria.fr/naudeber/deephyperx:rc2` and on Singularity `singularity run ./deephyperxtest_latest.sif`. 

Thank you!

**Comment by nshaud** [comment]
Hum, yeah, looks like there is a problem with the Docker image. The one from the registry is very old, you should build your own using the provided Dockerfile:
```
docker build . -t deephyperx:latest
```

**Comment by 5MI7th3MI6** [comment]
Thanks, It works when I build it with the Docker file. However, when I convert that file to Singularity, I get the same issue. 
![image](https://user-images.githubusercontent.com/68974383/116332649-27d7eb80-a7a0-11eb-97f0-3728c6e1c685.png)

**Comment by nshaud** [comment]
I don't know what `singularity` is. Build your image using the Dockerfile so that it is up to date with the master branch and you should be fine.
